name: cryptowave
description: "CryptoWave Application"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI and Presentation
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  intl: ^0.19.0
  lottie: ^3.3.1

  # State Management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # Networking
  http: ^1.4.0

  # Data Handling and Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Dependency Injection
  get_it: ^7.6.7

  # Navigation and Routing
  navigation_history_observer: ^1.1.0

  # Configuration
  flutter_dotenv: ^5.2.1

  # Logging and Debugging
  logger: ^2.0.2+1

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.6

  # Linting and Analysis
  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0

  # Code Generation
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/
    - .env
